version: '3.8'

services:
  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: my-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: