version: '3.8'

services:
  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    container_name: my-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"

  tracker:
    build:
      context: ./backend/tracker
      dockerfile: Dockerfile
    container_name: my-tracker
    restart: unless-stopped
    env_file:
      - ".env"
    depends_on:
      - rabbitmq
      - db

  db-handler:
    build:
      context: ./backend/db-handler
      dockerfile: Dockerfile
    container_name: my-db-handler
    restart: unless-stopped
    env_file:
      - ".env"
    depends_on:
      - rabbitmq
      - db

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: my-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file:
      - ".env"
    depends_on:
      - db

volumes:
  postgres_data: